---
package_url: http://ftp.fau.de/eclipse/technology/epp/downloads/release/2019-03/R/eclipse-cpp-2019-03-R-linux-gtk-x86_64.tar.gz
package_sha: sha512:32a74771dd9588ee2fd1b2a92ea0d6b875599eaad8c4a9b2cd85f3a45a545902332a1cb2fc29f984535339039534b20e346c0f547a16432759b74b4c2e056247
